#cloud-config

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - nfs-common

write_files:
  - path: /usr/local/bin/kubectl-install.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      echo "Installing kubectl..."

      mkdir -p /etc/apt/keyrings

      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key \
      | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" \
      > /etc/apt/sources.list.d/kubernetes.list

      apt update
      apt install -y kubectl

      echo "Creating kube config directory..."

      mkdir -p /root/.kube
      touch /root/.kube/config

      chmod 700 /root/.kube
      chmod 600 /root/.kube/config

      echo "kubectl client setup complete"

runcmd:
  - bash /usr/local/bin/kubectl-install.sh