apiVersion: v1
kind: Pod
metadata:
  name: nfs-direct
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /mnt
      name: nfs
  volumes:
  - name: nfs
    nfs:
      server: 192.168.2.9
      path: /srv/nfs/kubedata