apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  namespace: upload-demo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: upload-storage
  resources:
    requests:
      storage: 1Gi