apiVersion: v1
kind: Namespace
metadata: 
  name: ns-a
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  namespace: ns-a
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]