apiVersion: v1 
kind: ConfigMap
metadata:
  name: postgress-config
  namespace: db-demo-ns
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
  DB_SSLMODE: disable
  APP_PORT: "8080"

---
apiVersion: v1
kind: Secret 
metadata:
  name: postgres-secret
  namespace: db-demo-ns
type: Opaque
stringData:
  POSTGRES_PASSWORD: apppassword
  DB_PASSWORD: apppassword

