apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nginx-storage
  resources:
    requests:
      storage: 1Gi