apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-nfs
  namespace: upload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader-nfs
  template:
    metadata:
      labels:
        app: uploader-nfs
    spec:
      containers:
        - name: app
          image: go-file-uploader:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: uploads
              mountPath: /data/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: shared-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uploader-nfs
  namespace: upload-demo
spec:
  selector:
    app: uploader-nfs
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
