apiVersion: v1
kind: Pod
metadata:
  name: nginx-file-app
  namespace: demo
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: nginx-file-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: binary-config
      mountPath: /usr/share/nginx/html/config
      readOnly: true
    ports:
      - containerPort: 80
    

  volumes:
  - name: binary-config
    configMap:
      name: myapp-file-cm
