apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gofile-store-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofile-store-storage-pvc-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gofile-store
  template:
    metadata:
      labels:
        app: gofile-store
    spec:
      # Replace worker-1 with your actual node hostname label value
      nodeSelector:
        kubernetes.io/hostname: k8s-worker

      containers:
        - name: gofile-store
          image: docker.io/jpalaparthi/gofile-store:1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: host-storage
              mountPath: /data/storage

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: host-storage
          persistentVolumeClaim:
            claimName: gofile-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gofile-store
  namespace: demo
spec:
  type: NodePort
  selector:
    app: gofile-store
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080